%YAML:1.0
# data
# change the following directory to the dataset directory
dataset_dir: /media/mt/F418BADF18BA9FD2/KITTI/odometry/data_odometry_gray/dataset/sequences/03
groundtruth_dir: /media/mt/F418BADF18BA9FD2/KITTI/odometry/data_odometry_poses/dataset/poses/03.txt

#dataset_dir: /home/mt/Miller/VSLAM/VO/testing_datasets/KITTI/sequences/05
#groundtruth_dir: /home/mt/Miller/VSLAM/VO/testing_datasets/05.txt

# camera intrinsics
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

num_features: 150
num_features_init: 50
num_features_tracking: 50

