%YAML:1.0
# data
# change the following directory to the dataset directory
dataset_dir: /media/mt/F418BADF18BA9FD2/KITTI/odometry/data_odometry_gray/dataset/sequences/04
groundtruth_dir: /media/mt/F418BADF18BA9FD2/KITTI/odometry/data_odometry_poses/dataset/poses/04.txt
outputPoints_dir: /home/mt/Miller/VSLAM/VO/VSLAMVO/result/key_points.txt
# sets save_pointcloud to <=0 as false; any other int > 0 as true
save_pointcloud: 1
outputCloud_dir: /home/mt/Miller/VSLAM/VO/VSLAMVO/result/point_cloud.ply

#dataset_dir: /home/mt/Miller/VSLAM/VO/testing_datasets/KITTI/sequences/05
#groundtruth_dir: /home/mt/Miller/VSLAM/VO/testing_datasets/05.txt

# camera intrinsics
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

num_features: 150
num_features_init: 50
num_features_tracking: 50

